customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"

gui:
  scrollOffMargin: 8
  tabWidth: 2
  language: en
  timeFormat: 02 Jan
  showBottomLine: false
  filterMode: fuzzy
  statusPanelView: allBranchesLog

git:
  pagers:
    - pager: delta --dark --paging=never
    - pager: ydiff -p cat -s --wrap --width={{columnWidth}}
      colorArg: never
    - externalDiffCommand: difft --color=always
