return {
  -- {
  --   "monkoose/neocodeium",
  --   event = "VeryLazy",
  --   keymap = {},
  --   config = function()
  --     local neocodeium = require("neocodeium")
  --     neocodeium.setup()
  --     vim.keymap.set("i", "<Tab>", function()
  --       require("neocodeium").accept()
  --     end)
  --     vim.keymap.set("i", "<A-Right>", function()
  --       require("neocodeium").accept_word()
  --     end)
  --     vim.keymap.set("i", "<A-Down>", function()
  --       require("neocodeium").accept_line()
  --     end)
  --     vim.keymap.set("i", "<A-e>", function()
  --       require("neocodeium").cycle_or_complete()
  --     end)
  --     vim.keymap.set("i", "<A-r>", function()
  --       require("neocodeium").cycle_or_complete(-1)
  --     end)
  --     -- vim.keymap.set("i", "<A-c>", function()
  --     --   require("neocodeium").clear()
  --     -- end)
  --   end,
  -- },

  -- {
  --   "Exafunction/windsurf.vim",
  --   -- enabled = false,
  --   event = "BufEnter",
  -- },
}
