return {
  {
    "LazyVim/LazyVim",
    -- opts = { colorscheme = "catppuccin" },
    opts = { colorscheme = "catppuccin-mocha" },
    -- opts = { colorscheme = "tokyonight-moon" },
  },
  {
    "folke/tokyonight.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      transparent = true,
    },
  },
  { "catppuccin/nvim", name = "catppuccin" },
  { "AlexvZyl/nordic.nvim", name = "nordic" },
  -- recolor devicons to match theme
  {
    "rachartier/tiny-devicons-auto-colors.nvim",
    event = "UIEnter",
    dependencies = {
      { "nvim-tree/nvim-web-devicons", commit = "9154484705968658e9aab2b894d1b2a64bf9f83d" },
    },
    config = true,
  },

  -- main theme
  {
    "navarasu/onedark.nvim",
    lazy = false,
    priority = 1000,
  },
  { "rebelot/kanagawa.nvim" },
  { "nyoom-engineering/oxocarbon.nvim" },
  { "oxfist/night-owl.nvim" },
  { "ramojus/mellifluous.nvim" },
  { "xero/miasma.nvim" },
  { "zootedb0t/citruszest.nvim" },
  { "rafamadriz/neon" },
  { "kvrohit/mellow.nvim" },
  { "Everblush/everblush.nvim" },
  { "cryptomilk/nightcity.nvim" },
  { "rose-pine/neovim" },
  { "navarasu/onedark.nvim" },
  { "sainnhe/gruvbox-material" },
  { "projekt0n/github-nvim-theme" },
  { "sainnhe/everforest" },
  { "Mofiqul/vscode.nvim" },
  { "olimorris/onedarkpro.nvim" },
  { "craftzdog/solarized-osaka.nvim" },
  { "shaunsingh/nord.nvim" },
  { "tiagovla/tokyodark.nvim" },
  { "sainnhe/edge" },
  { "rmehri01/onenord.nvim" },
  { "bluz71/vim-nightfly-colors" },
  { "eldritch-theme/eldritch.nvim" },
  { "mcchrish/zenbones.nvim" },
  { "olivercederborg/poimandres.nvim" },
  { "mhartington/oceanic-next" },
  { "dgox16/oldworld.nvim" },
  { "sho-87/kanagawa-paper.nvim" },
  { "HoNamDuong/hybrid.nvim" },
  { "rockyzhang24/arctic.nvim" },
  { "Yazeed1s/oh-lucy.nvim" },
  { "kdheepak/monochrome.nvim" },
  { "aliqyan-21/darkvoid.nvim" },
  { "datsfilipe/vesper.nvim" },
  { "aliqyan-21/darkvoid.nvim" },
  { "kvrohit/substrata.nvim" },
  { "rktjmp/lush.nvim" },
}
